name: Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          az acr login --name suryaphpacr123
          docker build -t suryaphpacr123.azurecr.io/php-app:latest .
          docker push suryaphpacr123.azurecr.io/php-app:latest

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name php-app \
            --resource-group php-rg \
            --image suryaphpacr123.azurecr.io/php-app:latest
